# Generated by Django 5.0.1 on 2024-02-12 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autors', '0001_initial'),
        ('quotes_web_hw', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autors.author'),
        ),
        migrations.DeleteModel(
            name='Author',
        ),
    ]
