# Generated by Django 5.0.1 on 2024-02-12 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes_web_hw', '0002_alter_quote_author_delete_author'),
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='quote',
            name='tags',
            field=models.ManyToManyField(to='tags.tag'),
        ),
    ]
