version: "3.11"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: hw11
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1111
